# Run `pre-commit install` to install the pre-commit hooks.
#
# Run `pre-commit autoupdate` to update all the plugins here.
#
# See https://pre-commit.com for more information.

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-toml
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff
        language: system
        types: [python]
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
